language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "17.0.1"
deploy:
  provider: pages
  script: yarn install && yarn run deploy
  github-token: $GH_TOKEN
  skip_cleanup: true
  target_branch: gh-pages
  on:
    branch: main